INSERT INTO api_country (code, country) VALUES ('AF', 'Afghanistan');
INSERT INTO api_country (code, country) VALUES ('AL', 'Albania');
INSERT INTO api_country (code, country) VALUES ('DZ', 'Algeria');
INSERT INTO api_country (code, country) VALUES ('DS', 'American Samoa');
INSERT INTO api_country (code, country) VALUES ('AD', 'Andorra');
INSERT INTO api_country (code, country) VALUES ('AO', 'Angola');
INSERT INTO api_country (code, country) VALUES ('AI', 'Anguilla');
INSERT INTO api_country (code, country) VALUES ('AQ', 'Antarctica');
INSERT INTO api_country (code, country) VALUES ('AG', 'Antigua and Barbuda');
INSERT INTO api_country (code, country) VALUES ('AR', 'Argentina');
INSERT INTO api_country (code, country) VALUES ('AM', 'Armenia');
INSERT INTO api_country (code, country) VALUES ('AW', 'Aruba');
INSERT INTO api_country (code, country) VALUES ('AU', 'Australia');
INSERT INTO api_country (code, country) VALUES ('AT', 'Austria');
INSERT INTO api_country (code, country) VALUES ('AZ', 'Azerbaijan');
INSERT INTO api_country (code, country) VALUES ('BS', 'Bahamas');
INSERT INTO api_country (code, country) VALUES ('BH', 'Bahrain');
INSERT INTO api_country (code, country) VALUES ('BD', 'Bangladesh');
INSERT INTO api_country (code, country) VALUES ('BB', 'Barbados');
INSERT INTO api_country (code, country) VALUES ('BY', 'Belarus');
INSERT INTO api_country (code, country) VALUES ('BE', 'Belgium');
INSERT INTO api_country (code, country) VALUES ('BZ', 'Belize');
INSERT INTO api_country (code, country) VALUES ('BJ', 'Benin');
INSERT INTO api_country (code, country) VALUES ('BM', 'Bermuda');
INSERT INTO api_country (code, country) VALUES ('BT', 'Bhutan');
INSERT INTO api_country (code, country) VALUES ('BO', 'Bolivia');
INSERT INTO api_country (code, country) VALUES ('BA', 'Bosnia and Herzegovina');
INSERT INTO api_country (code, country) VALUES ('BW', 'Botswana');
INSERT INTO api_country (code, country) VALUES ('BV', 'Bouvet Island');
INSERT INTO api_country (code, country) VALUES ('BR', 'Brazil');
INSERT INTO api_country (code, country) VALUES ('IO', 'British Indian Ocean Territory');
INSERT INTO api_country (code, country) VALUES ('BN', 'Brunei Darussalam');
INSERT INTO api_country (code, country) VALUES ('BG', 'Bulgaria');
INSERT INTO api_country (code, country) VALUES ('BF', 'Burkina Faso');
INSERT INTO api_country (code, country) VALUES ('BI', 'Burundi');
INSERT INTO api_country (code, country) VALUES ('KH', 'Cambodia');
INSERT INTO api_country (code, country) VALUES ('CM', 'Cameroon');
INSERT INTO api_country (code, country) VALUES ('CA', 'Canada');
INSERT INTO api_country (code, country) VALUES ('CV', 'Cape Verde');
INSERT INTO api_country (code, country) VALUES ('KY', 'Cayman Islands');
INSERT INTO api_country (code, country) VALUES ('CF', 'Central African Republic');
INSERT INTO api_country (code, country) VALUES ('TD', 'Chad');
INSERT INTO api_country (code, country) VALUES ('CL', 'Chile');
INSERT INTO api_country (code, country) VALUES ('CN', 'China');
INSERT INTO api_country (code, country) VALUES ('CX', 'Christmas Island');
INSERT INTO api_country (code, country) VALUES ('CC', 'Cocos (Keeling) Islands');
INSERT INTO api_country (code, country) VALUES ('CO', 'Colombia');
INSERT INTO api_country (code, country) VALUES ('KM', 'Comoros');
INSERT INTO api_country (code, country) VALUES ('CG', 'Congo');
INSERT INTO api_country (code, country) VALUES ('CK', 'Cook Islands');
INSERT INTO api_country (code, country) VALUES ('CR', 'Costa Rica');
INSERT INTO api_country (code, country) VALUES ('HR', 'Croatia (Hrvatska)');
INSERT INTO api_country (code, country) VALUES ('CU', 'Cuba');
INSERT INTO api_country (code, country) VALUES ('CY', 'Cyprus');
INSERT INTO api_country (code, country) VALUES ('CZ', 'Czech Republic');
INSERT INTO api_country (code, country) VALUES ('DK', 'Denmark');
INSERT INTO api_country (code, country) VALUES ('DJ', 'Djibouti');
INSERT INTO api_country (code, country) VALUES ('DM', 'Dominica');
INSERT INTO api_country (code, country) VALUES ('DO', 'Dominican Republic');
INSERT INTO api_country (code, country) VALUES ('TP', 'East Timor');
INSERT INTO api_country (code, country) VALUES ('EC', 'Ecuador');
INSERT INTO api_country (code, country) VALUES ('EG', 'Egypt');
INSERT INTO api_country (code, country) VALUES ('SV', 'El Salvador');
INSERT INTO api_country (code, country) VALUES ('GQ', 'Equatorial Guinea');
INSERT INTO api_country (code, country) VALUES ('ER', 'Eritrea');
INSERT INTO api_country (code, country) VALUES ('EE', 'Estonia');
INSERT INTO api_country (code, country) VALUES ('ET', 'Ethiopia');
INSERT INTO api_country (code, country) VALUES ('FK', 'Falkland Islands (Malvinas)');
INSERT INTO api_country (code, country) VALUES ('FO', 'Faroe Islands');
INSERT INTO api_country (code, country) VALUES ('FJ', 'Fiji');
INSERT INTO api_country (code, country) VALUES ('FI', 'Finland');
INSERT INTO api_country (code, country) VALUES ('FR', 'France');
INSERT INTO api_country (code, country) VALUES ('FX', 'France, Metropolitan');
INSERT INTO api_country (code, country) VALUES ('GF', 'French Guiana');
INSERT INTO api_country (code, country) VALUES ('PF', 'French Polynesia');
INSERT INTO api_country (code, country) VALUES ('TF', 'French Southern Territories');
INSERT INTO api_country (code, country) VALUES ('GA', 'Gabon');
INSERT INTO api_country (code, country) VALUES ('GM', 'Gambia');
INSERT INTO api_country (code, country) VALUES ('GE', 'Georgia');
INSERT INTO api_country (code, country) VALUES ('DE', 'Germany');
INSERT INTO api_country (code, country) VALUES ('GH', 'Ghana');
INSERT INTO api_country (code, country) VALUES ('GI', 'Gibraltar');
INSERT INTO api_country (code, country) VALUES ('GK', 'Guernsey');
INSERT INTO api_country (code, country) VALUES ('GR', 'Greece');
INSERT INTO api_country (code, country) VALUES ('GL', 'Greenland');
INSERT INTO api_country (code, country) VALUES ('GD', 'Grenada');
INSERT INTO api_country (code, country) VALUES ('GP', 'Guadeloupe');
INSERT INTO api_country (code, country) VALUES ('GU', 'Guam');
INSERT INTO api_country (code, country) VALUES ('GT', 'Guatemala');
INSERT INTO api_country (code, country) VALUES ('GN', 'Guinea');
INSERT INTO api_country (code, country) VALUES ('GW', 'Guinea-Bissau');
INSERT INTO api_country (code, country) VALUES ('GY', 'Guyana');
INSERT INTO api_country (code, country) VALUES ('HT', 'Haiti');
INSERT INTO api_country (code, country) VALUES ('HM', 'Heard and Mc Donald Islands');
INSERT INTO api_country (code, country) VALUES ('HN', 'Honduras');
INSERT INTO api_country (code, country) VALUES ('HK', 'Hong Kong');
INSERT INTO api_country (code, country) VALUES ('HU', 'Hungary');
INSERT INTO api_country (code, country) VALUES ('IS', 'Iceland');
INSERT INTO api_country (code, country) VALUES ('IN', 'India');
INSERT INTO api_country (code, country) VALUES ('IM', 'Isle of Man');
INSERT INTO api_country (code, country) VALUES ('ID', 'Indonesia');
INSERT INTO api_country (code, country) VALUES ('IR', 'Iran (Islamic Republic of)');
INSERT INTO api_country (code, country) VALUES ('IQ', 'Iraq');
INSERT INTO api_country (code, country) VALUES ('IE', 'Ireland');
INSERT INTO api_country (code, country) VALUES ('IL', 'Israel');
INSERT INTO api_country (code, country) VALUES ('IT', 'Italy');
INSERT INTO api_country (code, country) VALUES ('CI', 'Ivory Coast');
INSERT INTO api_country (code, country) VALUES ('JE', 'Jersey');
INSERT INTO api_country (code, country) VALUES ('JM', 'Jamaica');
INSERT INTO api_country (code, country) VALUES ('JP', 'Japan');
INSERT INTO api_country (code, country) VALUES ('JO', 'Jordan');
INSERT INTO api_country (code, country) VALUES ('KZ', 'Kazakhstan');
INSERT INTO api_country (code, country) VALUES ('KE', 'Kenya');
INSERT INTO api_country (code, country) VALUES ('KI', 'Kiribati');
INSERT INTO api_country (code, country) VALUES ('KP', 'Korea, Democratic People''s Republic of');
INSERT INTO api_country (code, country) VALUES ('KR', 'Korea, Republic of');
INSERT INTO api_country (code, country) VALUES ('XK', 'Kosovo');
INSERT INTO api_country (code, country) VALUES ('KW', 'Kuwait');
INSERT INTO api_country (code, country) VALUES ('KG', 'Kyrgyzstan');
INSERT INTO api_country (code, country) VALUES ('LA', 'Lao People''s Democratic Republic');
INSERT INTO api_country (code, country) VALUES ('LV', 'Latvia');
INSERT INTO api_country (code, country) VALUES ('LB', 'Lebanon');
INSERT INTO api_country (code, country) VALUES ('LS', 'Lesotho');
INSERT INTO api_country (code, country) VALUES ('LR', 'Liberia');
INSERT INTO api_country (code, country) VALUES ('LY', 'Libyan Arab Jamahiriya');
INSERT INTO api_country (code, country) VALUES ('LI', 'Liechtenstein');
INSERT INTO api_country (code, country) VALUES ('LT', 'Lithuania');
INSERT INTO api_country (code, country) VALUES ('LU', 'Luxembourg');
INSERT INTO api_country (code, country) VALUES ('MO', 'Macau');
INSERT INTO api_country (code, country) VALUES ('MK', 'Macedonia');
INSERT INTO api_country (code, country) VALUES ('MG', 'Madagascar');
INSERT INTO api_country (code, country) VALUES ('MW', 'Malawi');
INSERT INTO api_country (code, country) VALUES ('MY', 'Malaysia');
INSERT INTO api_country (code, country) VALUES ('MV', 'Maldives');
INSERT INTO api_country (code, country) VALUES ('ML', 'Mali');
INSERT INTO api_country (code, country) VALUES ('MT', 'Malta');
INSERT INTO api_country (code, country) VALUES ('MH', 'Marshall Islands');
INSERT INTO api_country (code, country) VALUES ('MQ', 'Martinique');
INSERT INTO api_country (code, country) VALUES ('MR', 'Mauritania');
INSERT INTO api_country (code, country) VALUES ('MU', 'Mauritius');
INSERT INTO api_country (code, country) VALUES ('TY', 'Mayotte');
INSERT INTO api_country (code, country) VALUES ('MX', 'Mexico');
INSERT INTO api_country (code, country) VALUES ('FM', 'Micronesia, Federated States of');
INSERT INTO api_country (code, country) VALUES ('MD', 'Moldova, Republic of');
INSERT INTO api_country (code, country) VALUES ('MC', 'Monaco');
INSERT INTO api_country (code, country) VALUES ('MN', 'Mongolia');
INSERT INTO api_country (code, country) VALUES ('ME', 'Montenegro');
INSERT INTO api_country (code, country) VALUES ('MS', 'Montserrat');
INSERT INTO api_country (code, country) VALUES ('MA', 'Morocco');
INSERT INTO api_country (code, country) VALUES ('MZ', 'Mozambique');
INSERT INTO api_country (code, country) VALUES ('MM', 'Myanmar');
INSERT INTO api_country (code, country) VALUES ('NA', 'Namibia');
INSERT INTO api_country (code, country) VALUES ('NR', 'Nauru');
INSERT INTO api_country (code, country) VALUES ('NP', 'Nepal');
INSERT INTO api_country (code, country) VALUES ('NL', 'Netherlands');
INSERT INTO api_country (code, country) VALUES ('AN', 'Netherlands Antilles');
INSERT INTO api_country (code, country) VALUES ('NC', 'New Caledonia');
INSERT INTO api_country (code, country) VALUES ('NZ', 'New Zealand');
INSERT INTO api_country (code, country) VALUES ('NI', 'Nicaragua');
INSERT INTO api_country (code, country) VALUES ('NE', 'Niger');
INSERT INTO api_country (code, country) VALUES ('NG', 'Nigeria');
INSERT INTO api_country (code, country) VALUES ('NU', 'Niue');
INSERT INTO api_country (code, country) VALUES ('NF', 'Norfolk Island');
INSERT INTO api_country (code, country) VALUES ('MP', 'Northern Mariana Islands');
INSERT INTO api_country (code, country) VALUES ('NO', 'Norway');
INSERT INTO api_country (code, country) VALUES ('OM', 'Oman');
INSERT INTO api_country (code, country) VALUES ('PK', 'Pakistan');
INSERT INTO api_country (code, country) VALUES ('PW', 'Palau');
INSERT INTO api_country (code, country) VALUES ('PS', 'Palestine');
INSERT INTO api_country (code, country) VALUES ('PA', 'Panama');
INSERT INTO api_country (code, country) VALUES ('PG', 'Papua New Guinea');
INSERT INTO api_country (code, country) VALUES ('PY', 'Paraguay');
INSERT INTO api_country (code, country) VALUES ('PE', 'Peru');
INSERT INTO api_country (code, country) VALUES ('PH', 'Philippines');
INSERT INTO api_country (code, country) VALUES ('PN', 'Pitcairn');
INSERT INTO api_country (code, country) VALUES ('PL', 'Poland');
INSERT INTO api_country (code, country) VALUES ('PT', 'Portugal');
INSERT INTO api_country (code, country) VALUES ('PR', 'Puerto Rico');
INSERT INTO api_country (code, country) VALUES ('QA', 'Qatar');
INSERT INTO api_country (code, country) VALUES ('RE', 'Reunion');
INSERT INTO api_country (code, country) VALUES ('RO', 'Romania');
INSERT INTO api_country (code, country) VALUES ('RU', 'Russian Federation');
INSERT INTO api_country (code, country) VALUES ('RW', 'Rwanda');
INSERT INTO api_country (code, country) VALUES ('KN', 'Saint Kitts and Nevis');
INSERT INTO api_country (code, country) VALUES ('LC', 'Saint Lucia');
INSERT INTO api_country (code, country) VALUES ('VC', 'Saint Vincent and the Grenadines');
INSERT INTO api_country (code, country) VALUES ('WS', 'Samoa');
INSERT INTO api_country (code, country) VALUES ('SM', 'San Marino');
INSERT INTO api_country (code, country) VALUES ('ST', 'Sao Tome and Principe');
INSERT INTO api_country (code, country) VALUES ('SA', 'Saudi Arabia');
INSERT INTO api_country (code, country) VALUES ('SN', 'Senegal');
INSERT INTO api_country (code, country) VALUES ('RS', 'Serbia');
INSERT INTO api_country (code, country) VALUES ('SC', 'Seychelles');
INSERT INTO api_country (code, country) VALUES ('SL', 'Sierra Leone');
INSERT INTO api_country (code, country) VALUES ('SG', 'Singapore');
INSERT INTO api_country (code, country) VALUES ('SK', 'Slovakia');
INSERT INTO api_country (code, country) VALUES ('SI', 'Slovenia');
INSERT INTO api_country (code, country) VALUES ('SB', 'Solomon Islands');
INSERT INTO api_country (code, country) VALUES ('SO', 'Somalia');
INSERT INTO api_country (code, country) VALUES ('ZA', 'South Africa');
INSERT INTO api_country (code, country) VALUES ('GS', 'South Georgia South Sandwich Islands');
INSERT INTO api_country (code, country) VALUES ('ES', 'Spain');
INSERT INTO api_country (code, country) VALUES ('LK', 'Sri Lanka');
INSERT INTO api_country (code, country) VALUES ('SH', 'St. Helena');
INSERT INTO api_country (code, country) VALUES ('PM', 'St. Pierre and Miquelon');
INSERT INTO api_country (code, country) VALUES ('SD', 'Sudan');
INSERT INTO api_country (code, country) VALUES ('SR', 'Suriname');
INSERT INTO api_country (code, country) VALUES ('SJ', 'Svalbard and Jan Mayen Islands');
INSERT INTO api_country (code, country) VALUES ('SZ', 'Swaziland');
INSERT INTO api_country (code, country) VALUES ('SE', 'Sweden');
INSERT INTO api_country (code, country) VALUES ('CH', 'Switzerland');
INSERT INTO api_country (code, country) VALUES ('SY', 'Syrian Arab Republic');
INSERT INTO api_country (code, country) VALUES ('TW', 'Taiwan');
INSERT INTO api_country (code, country) VALUES ('TJ', 'Tajikistan');
INSERT INTO api_country (code, country) VALUES ('TZ', 'Tanzania, United Republic of');
INSERT INTO api_country (code, country) VALUES ('TH', 'Thailand');
INSERT INTO api_country (code, country) VALUES ('TG', 'Togo');
INSERT INTO api_country (code, country) VALUES ('TK', 'Tokelau');
INSERT INTO api_country (code, country) VALUES ('TO', 'Tonga');
INSERT INTO api_country (code, country) VALUES ('TT', 'Trinidad and Tobago');
INSERT INTO api_country (code, country) VALUES ('TN', 'Tunisia');
INSERT INTO api_country (code, country) VALUES ('TR', 'Turkey');
INSERT INTO api_country (code, country) VALUES ('TM', 'Turkmenistan');
INSERT INTO api_country (code, country) VALUES ('TC', 'Turks and Caicos Islands');
INSERT INTO api_country (code, country) VALUES ('TV', 'Tuvalu');
INSERT INTO api_country (code, country) VALUES ('UG', 'Uganda');
INSERT INTO api_country (code, country) VALUES ('UA', 'Ukraine');
INSERT INTO api_country (code, country) VALUES ('AE', 'United Arab Emirates');
INSERT INTO api_country (code, country) VALUES ('GB', 'United Kingdom');
INSERT INTO api_country (code, country) VALUES ('US', 'United States');
INSERT INTO api_country (code, country) VALUES ('UM', 'United States minor outlying islands');
INSERT INTO api_country (code, country) VALUES ('UY', 'Uruguay');
INSERT INTO api_country (code, country) VALUES ('UZ', 'Uzbekistan');
INSERT INTO api_country (code, country) VALUES ('VU', 'Vanuatu');
INSERT INTO api_country (code, country) VALUES ('VA', 'Vatican City State');
INSERT INTO api_country (code, country) VALUES ('VE', 'Venezuela');
INSERT INTO api_country (code, country) VALUES ('VN', 'Vietnam');
INSERT INTO api_country (code, country) VALUES ('VG', 'Virgin Islands (British)');
INSERT INTO api_country (code, country) VALUES ('VI', 'Virgin Islands (U.S.)');
INSERT INTO api_country (code, country) VALUES ('WF', 'Wallis and Futuna Islands');
INSERT INTO api_country (code, country) VALUES ('EH', 'Western Sahara');
INSERT INTO api_country (code, country) VALUES ('YE', 'Yemen');
INSERT INTO api_country (code, country) VALUES ('YU', 'Yugoslavia');
INSERT INTO api_country (code, country) VALUES ('ZR', 'Zaire');
INSERT INTO api_country (code, country) VALUES ('ZM', 'Zambia');
INSERT INTO api_country (code, country) VALUES ('ZW', 'Zimbabwe');