# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-15 11:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=255)),
                ('visible_from', models.DateField(auto_now=True)),
                ('visible_untill', models.DateField(null=True)),
            ],
        ),
    ]
