# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-15 11:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_crosslab', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=models.deletion.CASCADE, related_name='products', to='api.Category'))
            ],
        ),
    ]
