# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-15 13:05
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_skill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='level',
            field=models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)]),
        ),
    ]
