# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-15 13:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_category_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='engineer',
            name='languages',
            field=models.ManyToManyField(related_name='engineers', to='api.Language'),
        ),
        migrations.AddField(
            model_name='note',
            name='engineer',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='note', to='api.Engineer'),
            preserve_default=False,
        ),
    ]
