# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-07 20:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20151215_1424'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='visible_untill',
            new_name='visible_until',
        ),
        migrations.AlterField(
            model_name='engineer',
            name='vca_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='engineer',
            name='vca_number',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
