# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-13 13:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20160107_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='api.Product'),
        ),
        migrations.AlterUniqueTogether(
            name='skill',
            unique_together=set([('engineer', 'product')]),
        ),
    ]
