# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-25 11:46
from __future__ import unicode_literals

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20160113_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='engineer',
            name='image',
            field=models.ImageField(null=True, upload_to=api.models.upload_location),
        ),
    ]
