# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-27 14:06
from __future__ import unicode_literals

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_engineer_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to=api.models.upload_location),
        ),
        migrations.AlterField(
            model_name='engineer',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to=api.models.upload_location),
            preserve_default=False,
        ),
    ]
