# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-25 22:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20160201_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='engineer',
            name='type',
            field=models.SmallIntegerField(choices=[(0, 'FSS'), (1, 'ASP')], default=0),
            preserve_default=False,
        ),
    ]
