# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-14 12:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_engineer_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engineer',
            name='droppoint',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='engineer',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='engineer',
            name='phone',
            field=models.CharField(max_length=31),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
