# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-16 13:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20160314_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='is_fss',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='engineer',
            name='type',
            field=models.SmallIntegerField(choices=[(0, 'FSE'), (1, 'ASP')]),
        ),
    ]
