# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-31 11:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_auto_20160317_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engineer',
            name='type',
            field=models.SmallIntegerField(choices=[(0, 'FSE'), (1, 'ASP'), (2, 'RCE')]),
        ),
    ]
