insert into api_category (id, short_name, name, parent_id) values (1, 'VA', 'Atomic Absorption', null);
insert into api_category (id, short_name, name, parent_id) values (2, 'NV', 'Atomic Spectroscopy', null);
insert into api_category (id, short_name, name, parent_id) values (3, 'GA', 'Automated Electrophoresis', null);
insert into api_category (id, short_name, name, parent_id) values (4, 'MI', 'Automation Solutions', null);
insert into api_category (id, short_name, name, parent_id) values (5, 'TX', 'Bioanalyzer & TapeStation Solutions', null);
insert into api_category (id, short_name, name, parent_id) values (6, 'MO', 'BioMolecule Synthesis & Purification', null);
insert into api_category (id, short_name, name, parent_id) values (7, 'TX', 'Cancer Diagnostics (dako.com)', null);
insert into api_category (id, short_name, name, parent_id) values (8, 'CA', 'Capillary Electrophoresis & CE/MS', null);
insert into api_category (id, short_name, name, parent_id) values (9, 'KS', 'CGH & CGH+SNP Microarrays', null);
insert into api_category (id, short_name, name, parent_id) values (10, 'AZ', 'CRISPR/CAS', null);
insert into api_category (id, short_name, name, parent_id) values (11, 'MN', 'Dissolution', null);
insert into api_category (id, short_name, name, parent_id) values (12, 'NY', 'Electronic Measurement (keysight.com)', null);
insert into api_category (id, short_name, name, parent_id) values (13, 'CA', 'Epigenetic & Specialty Microarrays', null);
insert into api_category (id, short_name, name, parent_id) values (14, 'FL', 'FISH Probes', null);
insert into api_category (id, short_name, name, parent_id) values (15, 'DC', 'Flow Cytometry', null);
insert into api_category (id, short_name, name, parent_id) values (16, 'MI', 'Fluorescence', null);
insert into api_category (id, short_name, name, parent_id) values (17, 'GA', 'FTIR', null);
insert into api_category (id, short_name, name, parent_id) values (18, 'TX', 'Gas Chromatography', null);
insert into api_category (id, short_name, name, parent_id) values (19, 'NY', 'Gene Expression Microarrays', null);
insert into api_category (id, short_name, name, parent_id) values (20, 'FL', 'Genomics Product Design & Data Analysis', null);
insert into api_category (id, short_name, name, parent_id) values (21, 'FL', 'GPC/SEC', null);
insert into api_category (id, short_name, name, parent_id) values (22, 'VA', 'ICP-MS', null);
insert into api_category (id, short_name, name, parent_id) values (23, 'TN', 'ICP-OES', null);
insert into api_category (id, short_name, name, parent_id) values (24, 'OH', 'Immunohistochemistry', null);
insert into api_category (id, short_name, name, parent_id) values (25, 'TX', 'Lab Supplies', null);
insert into api_category (id, short_name, name, parent_id) values (26, 'WI', 'Liquid Chromatography', null);
insert into api_category (id, short_name, name, parent_id) values (27, 'IN', 'Mass Spectrometry', null);
insert into api_category (id, short_name, name, parent_id) values (28, 'KS', 'miRNA Microarrays', null);
insert into api_category (id, short_name, name, parent_id) values (29, 'TX', 'Molecular Pathology', null);
insert into api_category (id, short_name, name, parent_id) values (30, 'PA', 'Molecular Spectroscopy', null);
insert into api_category (id, short_name, name, parent_id) values (31, 'NM', 'MP-AES', null);
insert into api_category (id, short_name, name, parent_id) values (32, 'WA', 'Mutagenesis & Cloning', null);
insert into api_category (id, short_name, name, parent_id) values (33, 'IN', 'Next Generation Sequencing', null);
insert into api_category (id, short_name, name, parent_id) values (34, 'MA', 'Offgel Electrophoresis', null);
insert into api_category (id, short_name, name, parent_id) values (35, 'OH', 'Pathology Solutions', null);
insert into api_category (id, short_name, name, parent_id) values (36, 'CA', 'PCR & RT-PCR', null);
insert into api_category (id, short_name, name, parent_id) values (37, 'TN', 'pharmDx', null);
insert into api_category (id, short_name, name, parent_id) values (38, 'DC', 'Premium Refurbished Instruments', null);
insert into api_category (id, short_name, name, parent_id) values (39, 'NE', 'Protein Expression', null);
insert into api_category (id, short_name, name, parent_id) values (40, 'TN', 'qPCR', null);
insert into api_category (id, short_name, name, parent_id) values (41, 'TX', 'Sample Preparation', null);
insert into api_category (id, short_name, name, parent_id) values (42, 'OK', 'Services', null);
insert into api_category (id, short_name, name, parent_id) values (43, 'IL', 'Software & Informatics', null);
insert into api_category (id, short_name, name, parent_id) values (44, 'PA', 'Special Stains', null);
insert into api_category (id, short_name, name, parent_id) values (45, 'NE', 'Specific Proteins', null);
insert into api_category (id, short_name, name, parent_id) values (46, 'TX', 'UV-Vis & UV-Vis-NIR', null);
insert into api_category (id, short_name, name, parent_id) values (47, 'WA', 'Vacuum Technologies', null);
